/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet; 
import java.sql.SQLException; 
import java.util.ArrayList; 
import java.util.List; 
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JButton; 
import javax.swing.JComboBox; 
import javax.swing.JOptionPane; 
import javax.swing.JTable; 
import javax.swing.JTextField; 
import javax.swing.table.DefaultTableModel; 
import control.c_koneksi; 
import control.controllerToko; 
import model.m_toko;

/**
 *
 * @author Arischa Nur Fadilah
 */
public class home extends javax.swing.JFrame {
    controllerToko ctoko;
    List<m_toko>listdata = new ArrayList<>();

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        ctoko = new controllerToko (this);
        ctoko.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labeladmin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtadmin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbKategoriBrg = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbjenis = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        bersihkan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbCariKategori = new javax.swing.JComboBox<>();
        cari = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));
        jPanel1.setLayout(null);

        labeladmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labeladmin.setText("Admin : ");
        jPanel1.add(labeladmin);
        labeladmin.setBounds(10, 11, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Data Barang di Toko");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 30, 300, 40);

        txtadmin.setEditable(false);
        jPanel1.add(txtadmin);
        txtadmin.setBounds(70, 10, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 580, 80);

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Kode Barang");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 140, 30);
        jPanel2.add(txtkode);
        txtkode.setBounds(150, 10, 280, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nama Barang");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 50, 140, 30);
        jPanel2.add(txtNama);
        txtNama.setBounds(150, 50, 280, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Kategori Barang");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 90, 140, 30);

        cbKategoriBrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Baranglain" }));
        jPanel2.add(cbKategoriBrg);
        cbKategoriBrg.setBounds(150, 90, 280, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Packaging");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 130, 140, 30);

        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack" }));
        jPanel2.add(cbjenis);
        cbjenis.setBounds(150, 130, 280, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Harga Barang");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 170, 140, 30);
        jPanel2.add(txtharga);
        txtharga.setBounds(150, 170, 280, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 100, 450, 220);

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));
        jPanel3.setLayout(null);

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel3.add(simpan);
        simpan.setBounds(10, 10, 100, 30);

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        jPanel3.add(ubah);
        ubah.setBounds(10, 50, 100, 30);

        bersihkan.setText("Bersihkan");
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });
        jPanel3.add(bersihkan);
        bersihkan.setBounds(10, 90, 100, 30);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel3.add(hapus);
        hapus.setBounds(10, 130, 100, 30);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel3.add(keluar);
        keluar.setBounds(10, 170, 100, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(470, 100, 120, 220);

        jPanel4.setBackground(new java.awt.Color(204, 153, 255));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Pencarian Berdasarkan kategori makanan");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 0, 300, 50);

        cbCariKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Baranglain" }));
        jPanel4.add(cbCariKategori);
        cbCariKategori.setBounds(280, 10, 180, 30);

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel4.add(cari);
        cari.setBounds(470, 10, 100, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 330, 580, 50);

        jPanel5.setBackground(new java.awt.Color(204, 102, 255));
        jPanel5.setLayout(null);

        Tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Kategori", "Packaging", "Harga"
            }
        ));
        Tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel1);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 560, 130);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(10, 390, 580, 160);

        setSize(new java.awt.Dimension(614, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        ctoko.SimpanData();
        ctoko.isiTable();
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        ctoko.Ubah();
        ctoko.isiTable();
    }//GEN-LAST:event_ubahActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        ctoko.CariKategori();
        
    }//GEN-LAST:event_cariActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String user1 = login.user;
        txtadmin.setText(user1);
    }//GEN-LAST:event_formWindowOpened

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
        ctoko.Reset();
    }//GEN-LAST:event_bersihkanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        ctoko.Hapus();
        ctoko.isiTable();
    }//GEN-LAST:event_hapusActionPerformed

    private void Tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel1MouseClicked
        // TODO add your handling code here:
        int baris = Tabel1.getSelectedRow();
        ctoko.isiField(baris);
    }//GEN-LAST:event_Tabel1MouseClicked

    public JTextField getTxtKode(){ 
        return txtkode; 
    } 
    public JTextField getTxtNama(){ 
        return txtNama; 
    } 
    public JTextField getTxtHarga(){ 
        return txtharga; 
    } 
    public JComboBox getCbKategori(){ 
        return cbKategoriBrg; 
    } 
    public JComboBox getCbJenis(){ 
        return cbjenis; 
    } 
    public JComboBox getCbCariKategori(){ 
        return cbCariKategori; 
    } 
    public JButton getButtonHapus(){ 
        return hapus; 
    } 
    public JButton getButtonBersih(){ 
        return bersihkan; 
    } 
    public JButton getButtonSimpan(){ 
        return simpan; 
    } 
    public JButton getButtonUbah(){ 
        return ubah; 
    } 
    public JButton getButtonKeluar(){ 
        return keluar; 
    } 
    public JTable getTableData(){ 
        return Tabel1; 
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel1;
    private javax.swing.JButton bersihkan;
    private javax.swing.JButton cari;
    private javax.swing.JComboBox<String> cbCariKategori;
    private javax.swing.JComboBox<String> cbKategoriBrg;
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel labeladmin;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtadmin;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkode;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
